[tasks.test_wasm]
command = "wasm-pack"
args = ["test", "--headless", "--firefox"]

[tasks.test_native]
command = "cargo"
args = ["test"]

[tasks.test]
dependencies = ["test_native", "test_wasm"]

[tasks.check_native]
command = "cargo"
args = ["check"]

[tasks.check_wasm]
command = "cargo"
args = ["check", "--target", "wasm32-unknown-unknown"]

[tasks.check]
dependencies = ["check_native", "check_wasm"]
