[tasks.wasm_clean]
script_runner = "@shell"
script = '''
rm -rf web/bin ||:
'''

[tasks.clean]
command = "cargo"
args = ["clean"]
dependencies = ["wasm_clean"]

[tasks.format]
disabled = true

[tasks.test]
command = "wasm-pack"
args = ["test", "--headless", "--chrome"]

[tasks.check]
clear = true
command = "cargo"
args = ["check", "--target", "wasm32-unknown-unknown"]

[tasks.crate]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown"]

[tasks.build]
command = "wasm-bindgen"
clear = true
args = [
    "--out-dir",
    "web/bin",
    "--target",
    "web",
    "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/wasm32-unknown-unknown/release/${CARGO_MAKE_CRATE_NAME}.wasm",
]
dependencies = ["crate"]

[tasks.serve]
command = "miniserve"
args = ["web", "--port", "17645", "--index", "index.html"]

[tasks.watch]
command = "cargo"
args = [
    "watch",
    "-w",
    "../..",
    "-i",
    ".git",
    "-i",
    "target/*",
    "-i",
    ".vscode",
    "-i",
    "web/",
    "-s",
    "cargo make build",
]

[tasks.dev]
clear = true
run_task = { name = ["watch", "serve"], fork = true }
