[workspace]
members = ["crates/*"]

[package]
name = "rrr"
version = "0.2.0"
authors = ["Zageron <hello@adambryant.ca>"]
description = "Browser successor to FFR."
homepage = "https://github.com/flashflashrevolution/rrr"
repository = "https://github.com/flashflashrevolution/rrr"
readme = "readme.markdown"
license = "AGPL-3.0"
edition = "2021"
publish = false
rust-version = "1.66.0"

[[bin]]
name = "rrr"
path = "src/main.rs"

[features]
default = ["tui", "window"]
tui = ["rrr_tui"]
window = ["rrr_window"]

[dependencies]
clap = { version = "4.0.8", features = ["derive"] }
rrr_config = { path = "crates/rrr_config" }
rrr_tui = { path = "crates/rrr_tui", optional = true }
rrr_window = { path = "crates/rrr_window", optional = true }
