[tasks.docs]
workspace = false
clear = true
command = "cargo"
args = ["doc", "--all-features", "--no-deps", "--workspace"]

[tasks.wasm]
workspace = false
clear = true
command = "cargo"
args = ["make", "--cwd", "crates/rrr_wasm", "build"]

[tasks.release]
workspace = false
clear = true
command = "cargo"
args = ["build", "--release", "--bins"]

[tasks.build]
workspace = false
clear = true
command = "cargo"
args = ["build", "--bins"]

[tasks.install]
workspace = false
command = "cargo"
args = ["install", "--path", "."]

[tasks.run]
workspace = false
command = "cargo"
args = ["run", "--example", "native"]

[tasks.watch]
workspace = false
command = "cargo"
args = [
    "watch",
    "-w",
    ".",
    "-i",
    "**/*.markdown",
    "-i",
    "target/*",
    "-i",
    ".*",
    "-i",
    "rrr_wasm/*",
    "-s",
    "cargo make build",
]
