name: check

on:
  workflow_call:

env:
  CARGO_TERM_VERBOSE: true
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-Dwarnings"

jobs:
  check:
    name: Check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
        with:
          lfs: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy
          override: true
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: nightly-2024-05-05

      - uses: davidB/rust-cargo-make@v1
        with:
          version: "0.37.12"

      - name: Update Linux Dependencies
        run: sudo apt-get update
        if: ${{ runner.os == 'Linux' }}

      - name: Install Linux Dependencies
        run: sudo apt-get update && sudo apt-get update && sudo apt-get install -y libegl1-mesa-dev xorg-dev libasound2-dev
        if: ${{ runner.os == 'Linux' }}

      - name: ⚡ Cache
        uses: Swatinem/rust-cache@v2.7.3
        if: ${{ !env.ACT }}

      - name: Check
        working-directory: ${{ github.workspace }}
        run: cargo make check --makefile makefile.toml
