[package]
name = "rrr_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.25.0"
tui = "0.19.0"
unicode-width = "0.1"
rrr_config = { path = "../rrr_config" }
rrr_window = { path = "../rrr_window" }
